apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "gofire.fullname" . }}
  labels:
    {{- include "gofire.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "gofire.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gofire.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gofire.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "gofire.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GOFIRE_MASTER
              value: {{ .Values.gofire.isMaster | quote }}
            - name: GOFIRE_MASTER_HOST
              value: {{ .Values.gofire.masterHost | quote }}
            - name: GOFIRE_MASTER_PORT
              value: {{ .Values.gofire.masterPort | quote }}
            {{- if .Values.gofire.host }}
            - name: GOFIRE_HOST
              value: {{ .Values.gofire.host | quote }}
            {{- end }}
            - name: GOFIRE_PORT
              value: {{ .Values.gofire.port | quote }}
            - name: GOFIRE_MOCK_GPIO
              value: {{ .Values.gofire.mockGpio | quote }}
            - name: ENV
              value: {{ .Values.gofire.env }}
          ports:
            - name: http
              containerPort: {{ .Values.gofire.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /dev/mem
              name: devmem
            - mountPath: /dev/gpiomem
              name: devgpio
      volumes:
        - name: devmem
          hostPath:
            path: /dev/mem
        - name: devgpio
          hostPath:
            path: /dev/gpiomem
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
