name: "SignFire Controller"
description: "Located in the control case on the MindShark Sign"
solenoids:
  - name: main_supply
    type: supply
    mode: NC
    header_pin: 3
    metadata:
      voltage: 120
  - name: sign_0
    type: outlet
    header_pin: 5
    mode: NC
    metadata:
      voltage: 120
  - name: sign_1
    type: outlet
    header_pin: 7
    mode: NC
    metadata:
      voltage: 120
  - name: sign_2
    type: outlet
    header_pin: 11
    mode: NC
    metadata:
      voltage: 120
igniters:
  - name: pillar_crown_0
    type: glowfly
    header_pin: 13
    metadata:
      description: "Left Pillar Pilot Crown"
  - name: pillar_crown_1
    type: glowfly
    header_pin: 15
    metadata:
      description: "Right Pillar Pilot Crown"
  - name: sign_pilot_0
    type: glowfly
    header_pin: 19
    metadata:
      description: "Left side pilot lighter"
  - name: sign_pilot_1
    type: glowfly
    header_pin: 21
    metadata:
      description: "Right side pilot lighter"
